// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StorifyAPI.Migrations.Repository
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EmployeeCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9e4c537-87d6-810f-9a73-2754e9111870"),
                            Age = 24,
                            Code = "299159",
                            Name = "Mohamed Ashraf",
                            StoreId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        });
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MGroupId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<Guid>("MTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MTypeId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MTypeId");

                    b.ToTable("MaterialGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496edaa7-2a6e-481d-b160-c4a2e7333b87"),
                            Code = "Antibiotic",
                            GlobalName = "Antibiotics",
                            LocalName = "مضادات حيوية",
                            MTypeId = new Guid("496edaa7-b9eb-481d-b160-c4a2e7333b87")
                        },
                        new
                        {
                            Id = new Guid("c12bb473-7ef5-4d1b-aa11-ed60a12038b7"),
                            Code = "Painkiller",
                            GlobalName = "Painkillers",
                            LocalName = "مسكنات",
                            MTypeId = new Guid("496edaa7-b9eb-481d-b160-c4a2e7333b87")
                        },
                        new
                        {
                            Id = new Guid("3374144b-9876-45ba-aa75-d9a836a7a441"),
                            Code = "SparePart",
                            GlobalName = "Spare Parts",
                            LocalName = "قطع غيار",
                            MTypeId = new Guid("3374144b-ffdd-45ba-aa75-d9a836a7a441")
                        },
                        new
                        {
                            Id = new Guid("3374144b-ffdd-45ba-98ef-d9a836a7a441"),
                            Code = "Raw",
                            GlobalName = "Raw Materials",
                            LocalName = "مواد خام",
                            MTypeId = new Guid("3374144b-ffdd-45ba-aa75-d9a836a7a441")
                        });
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MItemId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<Guid>("MGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MGroupId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MGroupId");

                    b.ToTable("MaterialItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496edaa7-2a6e-481d-abcd-c4a2e7333b87"),
                            Code = "Antibiotic",
                            GlobalName = "Antibiotic",
                            LocalName = "مضاد حيوي",
                            MGroupId = new Guid("496edaa7-2a6e-481d-b160-c4a2e7333b87")
                        },
                        new
                        {
                            Id = new Guid("c12bb473-7ef5-4d1b-2245-ed60a12038b7"),
                            Code = "Painkiller",
                            GlobalName = "Painkiller",
                            LocalName = "مسكن",
                            MGroupId = new Guid("c12bb473-7ef5-4d1b-aa11-ed60a12038b7")
                        },
                        new
                        {
                            Id = new Guid("3374144b-9876-78ef-aa75-d9a836a7a441"),
                            Code = "SparePart",
                            GlobalName = "Spare Part",
                            LocalName = "قطعة غيار",
                            MGroupId = new Guid("3374144b-9876-45ba-aa75-d9a836a7a441")
                        },
                        new
                        {
                            Id = new Guid("3374144b-ad35-45ba-98ef-d9a836a7a441"),
                            Code = "Raw",
                            GlobalName = "Raw Material",
                            LocalName = "مادة خام",
                            MGroupId = new Guid("3374144b-ffdd-45ba-98ef-d9a836a7a441")
                        });
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MTypeID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MaterialType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496edaa7-b9eb-481d-b160-c4a2e7333b87"),
                            Code = "Drug",
                            GlobalName = "Drugs",
                            LocalName = "أدوية"
                        },
                        new
                        {
                            Id = new Guid("c12bb473-661f-4d1b-aa11-ed60a12038b7"),
                            Code = "Assets",
                            GlobalName = "Fixed Assets",
                            LocalName = "أصول ثايتة"
                        },
                        new
                        {
                            Id = new Guid("3374144b-ffdd-45ba-aa75-d9a836a7a441"),
                            Code = "Consumptions",
                            GlobalName = "Consumptions",
                            LocalName = "مستهلكات"
                        });
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MUnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MaterialUnit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496edaa7-76ea-481d-abcd-c4a2e7333b87"),
                            Code = "Box",
                            GlobalName = "Box ",
                            LocalName = "علبة"
                        },
                        new
                        {
                            Id = new Guid("c12bb473-adfe-4d1b-2245-ed60a12038b7"),
                            Code = "Bottle",
                            GlobalName = "Bottle",
                            LocalName = "زجاجة"
                        },
                        new
                        {
                            Id = new Guid("3374144b-1082-78ef-aa75-d9a836a7a441"),
                            Code = "Each",
                            GlobalName = "Each",
                            LocalName = "وحدة"
                        },
                        new
                        {
                            Id = new Guid("3374144b-ad35-45ba-afed-d9a836a7a441"),
                            Code = "Carton",
                            GlobalName = "Carton",
                            LocalName = "كارتونة"
                        });
                });

            modelBuilder.Entity("Entities.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StoreID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("StoreCode");

                    b.Property<int?>("CostCenterID")
                        .HasColumnType("int");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StoreGName");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StoreLName");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Code = "MainStore",
                            GlobalName = "Main Matrial Store",
                            LocalName = "مخزن العناصر الرئيسى"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialGroup", b =>
                {
                    b.HasOne("Entities.Models.Material.MaterialType", "MaterialType")
                        .WithMany("MaterialGroups")
                        .HasForeignKey("MTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialItem", b =>
                {
                    b.HasOne("Entities.Models.Material.MaterialGroup", "MaterialGroup")
                        .WithMany("MaterialItems")
                        .HasForeignKey("MGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialGroup");
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialGroup", b =>
                {
                    b.Navigation("MaterialItems");
                });

            modelBuilder.Entity("Entities.Models.Material.MaterialType", b =>
                {
                    b.Navigation("MaterialGroups");
                });

            modelBuilder.Entity("Entities.Models.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
